### ISSUE TITLE
Failing to build with go 1.22.1 and caddy 2.7.3

### ISSUE THREAD

**Issue by offbyone** [tailscale/caddy-tailscale#31]
It looks like a bunch of concurrency primitives are missing?

```
/home/offby1/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230504175454-7b0a1988a28f/pkg/sync/gate_unsafe.go:144:2: undefined: gopark
```

Full-ish logs:

```
$ go version
go version go1.22.1 linux/amd64
$ xcaddy build v2.7.3 --with github.com/tailscale/caddy-tailscale
... a bunch of go get
2024/03/23 21:04:54 [INFO] exec (timeout=0s): /usr/bin/go mod tidy -e
go: downloading github.com/onsi/gomega v1.27.8
go: downloading github.com/benbjohnson/clock v1.3.0
go: downloading github.com/google/go-tpm-tools v0.3.12
go: downloading github.com/aws/aws-sdk-go v1.44.307
go: downloading google.golang.org/api v0.132.0
go: downloading cloud.google.com/go/kms v1.15.0
go: downloading cloud.google.com/go v0.110.4
go: downloading cloud.google.com/go/iam v1.1.0
go: downloading golang.org/x/oauth2 v0.10.0
go: downloading github.com/googleapis/enterprise-certificate-proxy v0.2.5
go: downloading github.com/google/s2a-go v0.1.4
go: downloading cloud.google.com/go/compute v1.20.1
2024/03/23 21:04:59 [INFO] exec (timeout=0s): /usr/bin/go build -o /home/offby1/tmp/caddy -ldflags -w -s -trimpath
# gvisor.dev/gvisor/pkg/sync
/home/offby1/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230504175454-7b0a1988a28f/pkg/sync/gate_unsafe.go:114:3: undefined: goready
/home/offby1/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230504175454-7b0a1988a28f/pkg/sync/gate_unsafe.go:144:2: undefined: gopark
/home/offby1/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230504175454-7b0a1988a28f/pkg/sync/rwmutex_unsafe.go:76:3: undefined: semacquire
/home/offby1/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230504175454-7b0a1988a28f/pkg/sync/rwmutex_unsafe.go:102:4: undefined: semrelease
/home/offby1/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230504175454-7b0a1988a28f/pkg/sync/rwmutex_unsafe.go:152:3: undefined: semacquire
/home/offby1/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230504175454-7b0a1988a28f/pkg/sync/rwmutex_unsafe.go:179:3: undefined: semrelease
/home/offby1/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230504175454-7b0a1988a28f/pkg/sync/rwmutex_unsafe.go:207:3: undefined: semrelease
/home/offby1/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230504175454-7b0a1988a28f/pkg/sync/seqcount.go:87:6: undefined: canSpin
/home/offby1/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230504175454-7b0a1988a28f/pkg/sync/seqcount.go:89:4: undefined: doSpin
2024/03/23 21:05:12 [INFO] Cleaning up temporary folder: /home/offby1/.tmp/buildenv_2024-03-23-2104.2200051075
2024/03/23 21:05:12 [FATAL] exit status 1
```

**Comment by bradfitz** [comment]
I think you updated gvisor to the wrong branch. You want its go branch, not its default branch.

**Comment by offbyone** [comment]
I didn't install gvisor; the command to `xcaddy build` was the only thing I've issued.

**Comment by offbyone** [comment]
I tried it with caddy's latest tag as well (v2.7.6) to the same outcome.

**Comment by bradfitz** [comment]
@mholt do y'all update all your deps periodically by chance?

**Comment by willnorris** [comment]
looks to be fixed by #32

**Comment by mholt** [comment]
@bradfitz Yep, usually every few months or so, we'll at least update direct dependencies.
