### PR TITLE
Update caddy-tailscale version to 1.62

### LINKED ISSUE #31: Failing to build with go 1.22.1 and caddy 2.7.3
It looks like a bunch of concurrency primitives are missing?

```
/home/offby1/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230504175454-7b0a1988a28f/pkg/sync/gate_unsafe.go:144:2: undefined: gopark
```

Full-ish logs:

```
$ go version
go version go1.22.1 linux/amd64
$ xcaddy build v2.7.3 --with github.com/tailscale/caddy-tailscale
... a bunch of go get
2024/03/23 21:04:54 [INFO] exec (timeout=0s): /usr/bin/go mod tidy -e
go: downloading github.com/onsi/gomega v1.27.8
go: downloading github.com/benbjohnson/clock v1.3.0
go: downloading github.com/google/go-tpm-tools v0.3.12
go: downloading github.com/aws/aws-sdk-go v1.44.307
go: downloading google.golang.org/api v0.132.0
go: downloading cloud.google.com/go/kms v1.15.0
go: downloading cloud.google.com/go v0.110.4
go: downloading cloud.google.com/go/iam v1.1.0
go: downloading golang.org/x/oauth2 v0.10.0
go: downloading github.com/googleapis/enterprise-certificate-proxy v0.2.5
go: downloading github.com/google/s2a-go v0.1.4
go: downloading cloud.google.com/go/compute v1.20.1
2024/03/23 21:04:59 [INFO] exec (timeout=0s): /usr/bin/go build -o /home/offby1/tmp/caddy -ldflags -w -s -trimpath
# gvisor.dev/gvisor/pkg/sync
/home/offby1/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230504175454-7b0a1988a28f/pkg/sync/gate_unsafe.go:114:3: undefined: goready
/home/offby1/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230504175454-7b0a1988a28f/pkg/sync/gate_unsafe.go:144:2: undefined: gopark
/home/offby1/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230504175454-7b0a1988a28f/pkg/sync/rwmutex_unsafe.go:76:3: undefined: semacquire
/home/offby1/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230504175454-7b0a1988a28f/pkg/sync/rwmutex_unsafe.go:102:4: undefined: semrelease
/home/offby1/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230504175454-7b0a1988a28f/pkg/sync/rwmutex_unsafe.go:152:3: undefined: semacquire
/home/offby1/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230504175454-7b0a1988a28f/pkg/sync/rwmutex_unsafe.go:179:3: undefined: semrelease
/home/offby1/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230504175454-7b0a1988a28f/pkg/sync/rwmutex_unsafe.go:207:3: undefined: semrelease
/home/offby1/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230504175454-7b0a1988a28f/pkg/sync/seqcount.go:87:6: undefined: canSpin
/home/offby1/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230504175454-7b0a1988a28f/pkg/sync/seqcount.go:89:4: undefined: doSpin
2024/03/23 21:05:12 [INFO] Cleaning up temporary folder: /home/offby1/.tmp/buildenv_2024-03-23-2104.2200051075
2024/03/23 21:05:12 [FATAL] exit status 1
```

### PR DESCRIPTION
**Pull request by offbyone**
- bumps the golang version to 1.22.0 as well, incidentally
- the gvisor version in go.mod is the @go branch version, so
  it _should_ build

This probably fixes #31, at least it did for me

### CODE REVIEW

**Comment by offbyone** [comment]
@willnorris it looks like there's some kind of magical tailscale library version that this might not be ideal to replace. I cannot, for the life of me, figure out how to `go get` that and upgrade it; I am new to Go tooling, so perhaps there's some obvious way to achieve it?

File: go.mod [hunk 1]
```diff
@@ -1,74 +1,81 @@
 module github.com/tailscale/caddy-tailscale
 
-go 1.21
+go 1.22.0
+
+toolchain go1.22.1
```
Comment (willnorris) [inline go.mod:5]: we generally leave off the toolchain requirements, since we seldom have dependencies on specific toolchain version.  I'll go ahead and update that.

**Review by willnorris — APPROVED** [review]
this looks good, thanks!  The previous version we had wasn't anything special... it was just a go [pseudo version](https://go.dev/ref/mod#pseudo-versions) representing the HEAD commit at the time we last updated.  Updating to the actual 1.62.0 release is a good thing.

File: go.mod (hunk 1 above)
Comment (offbyone) [reply go.mod]: `go get -u` made this change, so I chose to trust the tool. Noted for the future :D
